/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.ClienteDAO;
import java.awt.Cursor;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import model.CampoNumeros;
import model.Cliente;

/**
 *
 * @author lucka
 */
public class RegistrarPagamento extends javax.swing.JFrame {

    ClienteDAO clienteDAO = new ClienteDAO();
    Cliente cliente = new Cliente();

    /**
     * Creates new form RegistrarPagamento
     */
    public RegistrarPagamento() {
        setIcon();
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        botaoRegistrarPagamento.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        campoDataDivida.setEditable(false);
        campoDataPagamentoMensal.setEditable(false);
        campoNome.setEditable(false);
        campoPorcentagem.setEditable(false);
        campoRendimentoPorcentagem.setEditable(false);
        campoRendimentoReais.setEditable(false);
        campoValorPagamentoMensal.setEditable(false);
        campoValorAtualDivida.setEditable(false);
        campoValorPagoPeloCliente.setDocument(new CampoNumeros(11));
        campoValorPagoPeloCliente.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        painelDadosCliente = new javax.swing.JPanel();
        campoNome = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoValorAtualDivida = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoDataDivida = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoPorcentagem = new javax.swing.JTextField();
        campoValorPagamentoMensal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoDataPagamentoMensal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableHistoricoPagamento = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        campoRendimentoPorcentagem = new javax.swing.JTextField();
        campoRendimentoReais = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        campoTotalEmprestimo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        campoValorPagoPeloCliente = new javax.swing.JTextField();
        botaoRegistrarPagamento = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        campoRendimentoTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de pagamento");
        setPreferredSize(new java.awt.Dimension(800, 550));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 550));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Dados do Cliente");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        painelDadosCliente.setBackground(new java.awt.Color(204, 204, 204));
        painelDadosCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        painelDadosCliente.setForeground(new java.awt.Color(0, 0, 0));

        campoNome.setBackground(new java.awt.Color(255, 255, 255));
        campoNome.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        campoNome.setForeground(new java.awt.Color(0, 0, 0));

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("%");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nome");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Valor Atual da Divida");

        campoValorAtualDivida.setBackground(new java.awt.Color(255, 255, 255));
        campoValorAtualDivida.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        campoValorAtualDivida.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Data Emprestimo");

        campoDataDivida.setBackground(new java.awt.Color(255, 255, 255));
        campoDataDivida.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        campoDataDivida.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Porcentagem Cobrada");

        campoPorcentagem.setBackground(new java.awt.Color(255, 255, 255));
        campoPorcentagem.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        campoPorcentagem.setForeground(new java.awt.Color(0, 0, 0));
        campoPorcentagem.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        campoValorPagamentoMensal.setBackground(new java.awt.Color(255, 255, 255));
        campoValorPagamentoMensal.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        campoValorPagamentoMensal.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Valor a ser Pago");

        campoDataPagamentoMensal.setBackground(new java.awt.Color(255, 255, 255));
        campoDataPagamentoMensal.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        campoDataPagamentoMensal.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Data De Pagamento");

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Dados da Divida");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout painelDadosClienteLayout = new javax.swing.GroupLayout(painelDadosCliente);
        painelDadosCliente.setLayout(painelDadosClienteLayout);
        painelDadosClienteLayout.setHorizontalGroup(
            painelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDadosClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(painelDadosClienteLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(campoValorPagamentoMensal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(painelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(painelDadosClienteLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(campoDataPagamentoMensal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
            .addGroup(painelDadosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelDadosClienteLayout.createSequentialGroup()
                        .addGroup(painelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoValorAtualDivida, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addGroup(painelDadosClienteLayout.createSequentialGroup()
                                .addComponent(campoPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelDadosClienteLayout.createSequentialGroup()
                                .addGroup(painelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(campoDataDivida))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelDadosClienteLayout.setVerticalGroup(
            painelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDadosClienteLayout.createSequentialGroup()
                .addGroup(painelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosClienteLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(painelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(painelDadosClienteLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(15, 15, 15)
                                .addGroup(painelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(painelDadosClienteLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(33, 33, 33))))
                            .addGroup(painelDadosClienteLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(33, 33, 33))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDadosClienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(campoDataDivida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoValorAtualDivida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(painelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelDadosClienteLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoDataPagamentoMensal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDadosClienteLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoValorPagamentoMensal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        tableHistoricoPagamento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tableHistoricoPagamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Valor Pago", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableHistoricoPagamento);

        jLabel14.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Histórico");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        campoRendimentoPorcentagem.setBackground(new java.awt.Color(255, 255, 255));
        campoRendimentoPorcentagem.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        campoRendimentoPorcentagem.setForeground(new java.awt.Color(0, 0, 0));
        campoRendimentoPorcentagem.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        campoRendimentoReais.setBackground(new java.awt.Color(255, 255, 255));
        campoRendimentoReais.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        campoRendimentoReais.setForeground(new java.awt.Color(0, 0, 0));

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("RENDIMENTO DOS");

        jLabel16.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("%");

        campoTotalEmprestimo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        campoTotalEmprestimo.setForeground(new java.awt.Color(0, 0, 0));
        campoTotalEmprestimo.setText("$$$$");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(campoRendimentoReais, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(campoRendimentoPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoTotalEmprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTotalEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoRendimentoReais, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoRendimentoPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Registrar novo pagamento:");

        campoValorPagoPeloCliente.setBackground(new java.awt.Color(255, 255, 255));
        campoValorPagoPeloCliente.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        campoValorPagoPeloCliente.setForeground(new java.awt.Color(0, 0, 0));
        campoValorPagoPeloCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoValorPagoPeloClienteActionPerformed(evt);
            }
        });
        campoValorPagoPeloCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoValorPagoPeloClienteKeyPressed(evt);
            }
        });

        botaoRegistrarPagamento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botaoRegistrarPagamento.setForeground(new java.awt.Color(0, 0, 0));
        botaoRegistrarPagamento.setText("<html>Registrar<br/>Pagamento</html>");
        botaoRegistrarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRegistrarPagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoValorPagoPeloCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(botaoRegistrarPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(botaoRegistrarPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoValorPagoPeloCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Rendimento Total Cliente:");
        jLabel17.setMaximumSize(new java.awt.Dimension(19, 20));
        jLabel17.setMinimumSize(new java.awt.Dimension(19, 20));
        jLabel17.setPreferredSize(new java.awt.Dimension(19, 20));

        campoRendimentoTotal.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        campoRendimentoTotal.setForeground(new java.awt.Color(0, 0, 0));
        campoRendimentoTotal.setText("$$$$$$$$$$$$$$$$$$");
        campoRendimentoTotal.setMaximumSize(new java.awt.Dimension(19, 20));
        campoRendimentoTotal.setMinimumSize(new java.awt.Dimension(19, 20));
        campoRendimentoTotal.setPreferredSize(new java.awt.Dimension(19, 20));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoRendimentoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(campoRendimentoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(painelDadosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelDadosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoValorPagoPeloClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoValorPagoPeloClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoValorPagoPeloClienteActionPerformed

    private void botaoRegistrarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRegistrarPagamentoActionPerformed
        registrarPagamento();
    }//GEN-LAST:event_botaoRegistrarPagamentoActionPerformed

    private void campoValorPagoPeloClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoValorPagoPeloClienteKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            registrarPagamento();
        }
    }//GEN-LAST:event_campoValorPagoPeloClienteKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarPagamento().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoRegistrarPagamento;
    private javax.swing.JTextField campoDataDivida;
    private javax.swing.JTextField campoDataPagamentoMensal;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoPorcentagem;
    private javax.swing.JTextField campoRendimentoPorcentagem;
    private javax.swing.JTextField campoRendimentoReais;
    private javax.swing.JLabel campoRendimentoTotal;
    private javax.swing.JLabel campoTotalEmprestimo;
    private javax.swing.JTextField campoValorAtualDivida;
    private javax.swing.JTextField campoValorPagamentoMensal;
    private javax.swing.JTextField campoValorPagoPeloCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painelDadosCliente;
    private javax.swing.JTable tableHistoricoPagamento;
    // End of variables declaration//GEN-END:variables

    private void fecharJanela() {
        dispose();
    }

    public void recebendo(String recebe) {
        cliente = clienteDAO.getPesquisarCliente(recebe);
        Double rendimentoTotal = clienteDAO.getRendimentoTotalCliente(cliente.getIdCliente());
        Double totalEmprestimo = cliente.getValorTotalEmprestimo();
        if (cliente.getRendimento() != null) {
            NumberFormat formatoMoeda = DecimalFormat.getCurrencyInstance(new Locale("pt", "BR"));
            Double rendimentoDivida = cliente.getRendimento();
            
            Double rendimentoPorcentagem = (cliente.getRendimento() * 100.0) / cliente.getValorTotalEmprestimo();
            String rendimentoPorcentagemString = String.format("%.2f", rendimentoPorcentagem);
            String rendimentoDividaFormatado = formatoMoeda.format(rendimentoDivida);
            campoRendimentoReais.setText(rendimentoDividaFormatado);
            campoRendimentoPorcentagem.setText(String.valueOf(rendimentoPorcentagemString));
        } else {
            campoRendimentoReais.setText("R$ 0,00");
            campoRendimentoPorcentagem.setText("0,00");
        }
        lerTabela(cliente);

        if (cliente.getValorTotalDivida() < 0) {
            cliente.setValorTotalDivida(0.0);
            cliente.setValorPagamentoMensal(0.0);
        }

        /*MASCARA DINHEIRO*/
        NumberFormat formatoMoeda = DecimalFormat.getCurrencyInstance(new Locale("pt", "BR"));
        String valorDividaFormatado = formatoMoeda.format(cliente.getValorTotalDivida());
        String valorPagamentoMensalFormatado = formatoMoeda.format(cliente.getValorPagamentoMensal());
        String rendimentoTotalFormatado = formatoMoeda.format(rendimentoTotal);
        String totalEmprestimoFormatado = formatoMoeda.format(totalEmprestimo);

        campoNome.setText(cliente.getNome());
        campoDataDivida.setText(cliente.getDataEmprestimo());
        campoValorAtualDivida.setText(valorDividaFormatado);
        campoValorPagamentoMensal.setText(valorPagamentoMensalFormatado);
        campoDataPagamentoMensal.setText(cliente.getDataPagamentoMensal());
        campoPorcentagem.setText(String.valueOf(cliente.getPorcentagem()));

        campoTotalEmprestimo.setText(String.valueOf(totalEmprestimoFormatado));
        campoRendimentoTotal.setText(rendimentoTotalFormatado);
    }

    public void validarPagamento(Double valorPago) {

        String padraoFormatacao = "dd/MM/yyyy";
        DateTimeFormatter formatador = DateTimeFormatter.ofPattern(padraoFormatacao);

        LocalDate dataPagamentoMensalLocalDate = LocalDate.parse(cliente.getDataPagamentoMensal(), formatador);
        LocalDate novaDataPagamentoMensalLocalDate = dataPagamentoMensalLocalDate.plus(Period.ofMonths(1));
        String novaDataPagamentoMensalString = novaDataPagamentoMensalLocalDate.format(formatador);

        cliente.setDataPagamentoMensal(novaDataPagamentoMensalString);
        cliente.setValorPagamentoMensal(valorPago);

        
        Boolean isPagamentoComValorExcedente = cliente.getValorPagamentoMensal() > (cliente.getValorTotalDivida() * (cliente.getPorcentagem() / 100.0));
        if (isPagamentoComValorExcedente) {
            cliente.setValorTotalDivida(cliente.getValorTotalDivida() - (valorPago - (cliente.getValorTotalDivida() * (Double.valueOf(cliente.getPorcentagem()) / 100))));
        }
        clienteDAO.registrarPagamento(cliente);
    }

    public void configurarTabela() {
        DefaultTableModel model = (DefaultTableModel) tableHistoricoPagamento.getModel();
        tableHistoricoPagamento.getTableHeader().setDefaultRenderer(new CenterRenderer());
        tableHistoricoPagamento.getColumnModel().getColumn(0).setCellRenderer(new CenterRenderer());
        tableHistoricoPagamento.getColumnModel().getColumn(1).setCellRenderer(new CenterRenderer());

        model.setNumRows(0);
    }

    public void lerTabela(Cliente historicoCliente) {
        configurarTabela();
        DefaultTableModel model = (DefaultTableModel) tableHistoricoPagamento.getModel();

        for (Cliente cliente : clienteDAO.getClientesHistorico(historicoCliente.getIdCliente())) {

            /*MASCARA DINHEIRO*/
            NumberFormat formatoMoeda = DecimalFormat.getCurrencyInstance(new Locale("pt", "BR"));
            String valorPagamentoMensalFormatado = formatoMoeda.format(cliente.getValorPagamentoMensal());

            model.addRow(new Object[]{
                valorPagamentoMensalFormatado,
                cliente.getDataPagamentoMensal()
            });
        }
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/assets/perspective_matte-373-128x128.png")));
    }
    
    public void registrarPagamento(){
        /*MASCARA DINHEIRO*/
        if (!campoValorPagoPeloCliente.getText().equals("")) {
            if (cliente.getValorTotalDivida() > 0) {
                Double confirmarValorPago = Double.valueOf(campoValorPagoPeloCliente.getText());
                NumberFormat formatoMoeda = DecimalFormat.getCurrencyInstance(new Locale("pt", "BR"));
                String confirmarValorPagoString = formatoMoeda.format(confirmarValorPago);
                String mensagem = "O VALOR PAGO DE " + confirmarValorPagoString + "\nESTA CORRETO ?";
                Integer confirmar = JOptionPane.showConfirmDialog(null, mensagem, "CONFIRME O VALOR!", JOptionPane.YES_NO_OPTION);
                if (confirmar == JOptionPane.YES_OPTION) {
                    Double valorPago = Double.valueOf(campoValorPagoPeloCliente.getText());
                    validarPagamento(valorPago);
                    fecharJanela();
//                    ClienteGUI clienteGUI = new ClienteGUI();
//                    clienteGUI.lerTabela();
                }
            } else {
                JOptionPane.showMessageDialog(null, "A divida desse cliente já foi finalizada", "ALERTA", 2);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Insira o valor pago no campo!", "ALERTA", 2);
        }
        campoValorPagoPeloCliente.setText("");
    }
}
